### ISSUE TITLE
Error in example in specification

### ISSUE THREAD

**Issue by ColinH** [arangodb/velocypack#25]
One of the example encodings for arrays has a mistake, the number of sub-values for type 9 is at the end, instead of after the byte length:
```
09
2c 00 00 00 00 00 00 00
31 32 33
09 00 00 00 00 00 00 00
0a 00 00 00 00 00 00 00
0b 00 00 00 00 00 00 00
03 00 00 00 00 00 00 00
```
If I understand the format correctly this is what it should look like:
```
09
2c 00 00 00 00 00 00 00
03 00 00 00 00 00 00 00
31 32 33
11 00 00 00 00 00 00 00
12 00 00 00 00 00 00 00
13 00 00 00 00 00 00 00
```

**Comment by jsteemann** [comment]
I think the description in the documentation for this array type is correct.
Arrays with 8-byte entries have the number of items stored at the end. This is in contrast to other array types, but it is a performance optimization to avoid later memmoves of a potentially very large chunk of memory.
According to the docs, the array representation should be like this (documentation on the left, the respective values for the example on the right):
```
0x09                                    09
BYTELENGTH in 8 bytes                   2c 00 00 00 00 00 00 00
sub VPack values                        31 32 33
INDEXTABLE with 8 byte per entry        09 00 00 00 00 00 00 00
                                        0a 00 00 00 00 00 00 00
                                        0b 00 00 00 00 00 00 00
NRITEMS in 8 bytes                      03 00 00 00 00 00 00 00
```

**Comment by ColinH** [comment]
Sorry, I didn't see the exception for 64bit lengths.

**Comment by ColinH** [comment]
I'm trying to understand the performance optimisation you mention; my first idea was to simply leave another 8 bytes free in the beginning, but you're probably doing something like this to obtain a more compact encoding:

* Encode with 1 byte size
* If the 1 byte length overflows, switch to 2 byte size and memmove a small block
* if the 2 byte length overflows, switch to 4 byte size and memmove a 64K block
* If the 4 byte length overflows, switch to 8 byte size and re-use what was previously the space for the 4 byte nritems as second half of the 8 byte size, this prevents the memmove, and add nritems to the end when done

**Comment by jsteemann** [comment]
It's a bit different.
For compound values (arrays and objects) first there is a generic type byte (0x06 for or 0x0b) written as the first byte. That type byte may be patched later when it is clear how big the array/object actually is. 
After the type byte, we add 8 null bytes as a buffer. The actual values are build up in memory behind behind this buffer, starting at byte offset 9. While building up the actual values, no memmove will be done. When the array/object is finally closed, we know its size and actual space requirements, and then there may be a memmove from byte offset 9 to lower byte offsets to save space. This memmove is normally not performed for arrays with byte length 4 or 8 because it would require moving a significant amount of memory.

**Comment by ColinH** [comment]
Ok, thank you for elaborating!
