### ISSUE TITLE
`json-to-vpack` producing compact output with `--no-compact` flag for maps with 1 item

### ISSUE THREAD

**Issue by davechallis** [arangodb/velocypack#41]
Only a very minor thing, but I noticed that using `json-to-vpack` with the `--no-compact` flag specified still produces compact output for the JSON maps that only contain a single member, for example:

    $ echo '{"a":1}'> input.json && ./json-to-vpack --no-compact --hex input.json output.vpack && cat output.vpack
    Successfully converted JSON infile 'input.json'
    JSON Infile size:    8
    VPack Outfile size:  6
    0x14 0x06 0x41 0x61 0x31 0x01

**Comment by jsteemann** [comment]
I think this is "intentional".
`json-to-vpack` correctly takes the input of either `--compact` or `--no-compact` and passes it on.
However, in VelocyPack we always try to automatically use the smallest representation possible. And when a Builder constructs an object with a single member, it will simply always use the compact representation, because it is smaller than the indexed representation:
https://github.com/arangodb/velocypack/blob/master/src/Builder.cpp#L559

I am a bit reluctant to change this, because I would consider this a "feature". There is no value (except educational) for having an index-table representation of an object with a single member.

**Comment by davechallis** [comment]
No worries in that case, I can see the rationale behind it. I've mostly just been using the script to generate sample vpack for a serializer I've been working on, so not really an issue.

**Comment by jsteemann** [comment]
Got it. Out of curiosity, what language is the serializer written in and is it (going to be) an open source project?

**Comment by davechallis** [comment]
@jsteemann I'm in the early stages of working on a serializer/deserializer in Rust, it'll definitely be open sourced as soon as I get past the initial stages. There are a couple of client libraries out there, but they all use HTTP/JSON from what I remember, so thought being able to support vpack as well might be useful.

**Comment by jsteemann** [comment]
Cool, thanks for letting us know!
