### ISSUE TITLE
Documentation request: Explain the role of Attribute Translators

### ISSUE THREAD

**Issue by lumieria** [arangodb/velocypack#61]
This code:
`
std::string key=result->slices().front().get("_key").copyString();
`
from this page:
https://www.arangodb.com/2017/11/introduction-fuerte-arangodb-c-plus-plus-driver/

Is causing the app to terminate with the following exception:
Cannot execute operation without attribute translator

In looking around, I can't seem to find any indication of how to provide what it is looking for, or otherwise access the value of _key.

Can you provide an example for this?

Thank you!

**Comment by jsteemann** [comment]
Objects in VelocyPack can store object keys as VelocyPack strings or VelocyPack integers.
For example, in the object
```
{"foo":1,"bar":2}
```
the objet keys are "foo" and "bar". Normally, those will be stored using VelocyPack string types, i.e. `0x43` in this case (string with length 3).
However, to save space, VelocyPack also supports storing common attributes using small-sized integers. This is an optional feature, and it is only used if an `AttributeTranslator` has been declared when building objects.
The purpose of an AttributeTranslator is to translate from string keys to integer keys, and vice versa.

In ArangoDB (the server) we use an AttributeTranslator with the following mappings:
* `"_key"`: int(1)
* `"_rev"`: int(2)
* `"_id"`: int(3)
* `"_from"`: int(4)
* `"_to"`: int(5)
We do this because the first three attributes occur in all ArangoDB documents, and the latter ones occur in all edges. Thus using the AttributeTranslator helps us to reduce storage space for documents.

I guess in your specific situation you are receiving VelocyPack sent by the ArangoDB server, and in case you want to decipher it, you need to set up an AttributeTranslator with the exact same mapping.

Once you have set up such AttributeTranslator, you can store the pointer to it in the VelocyPack::Options::Defaults.attributeTranslator static variable, so it is used globally in your application.

**Comment by lumieria** [comment]
There's a good workaround here where I cross-posted the question: [https://github.com/arangodb/fuerte/issues/24](https://github.com/arangodb/fuerte/issues/24)
