### ISSUE TITLE
std::shared_ptr<arangodb::velocypack::Builder> Slice invalid

### ISSUE THREAD

**Issue by kapilpipaliya** [arangodb/velocypack#63]
```
auto c = arangodb::velocypack::Collection::merge( a.slice(), b.slice(), true, false);
c.slice();
```
returns invalid slice.

**Comment by kapilpipaliya** [comment]
sorry i was returning a's slice from function. but it was invalid:
```
  arangodb::velocypack::ValueLength nr = parser.parse(json);
  std::shared_ptr<arangodb::velocypack::Builder> b = parser.steal();
  return b->slice();
```
but until now it was working.

**Comment by jsteemann** [comment]
The problem with returning a Slice from a function is that a Slice is not owning the data it points to.
If the data is owned by a variable local to the function, this is undefined behavior, and this also hasn't changed recently. It always was undefined behavior, but, it may have worked by accident.

The best way to fix this issue is to make your function return a `Builder` or a shared_ptr to the `Builder` instead of a `Slice`. That way the ownership can be passed back to the function's caller safely. The caller can then call `slice()` on that Builder safely.

Additionally, I suggest using tools such as the Google sanitizers (ASan, UBSan) to find such problematic code in your application at runtime.

**Comment by kapilpipaliya** [comment]
Thank you so much for very helpful response.
